### ISSUE TITLE
Wrong JSON path

### ISSUE THREAD

**Issue by bchatard** [DutchRican/cli_spinner#1]
Hi,

I try to use your lib, but the following error occurred
```
FileSystemException: Cannot open file, path = '/Users/bchatard/Projects/my-poject-dart/lib/src/spinners/spinners.json' (OS Error: No such file or directory, errno = 2)
```

The path point to my working dir instead of pub dir

**Comment by DutchRican** [comment]
hi there, sorry about that. Wrote that just to learn some dart and had not looked at it in a whole while. 
This should be fixed now, it is not using a json file for the spinners anymore but rather just exporting a list.
v1.0.4 should do the trick for you.
